package com.mycompany.processpassword;
// Generated May 22, 2018 9:55:07 PM by Hibernate Tools 4.3.1



/**
 * Cuentas generated by hbm2java
 */
public class Cuentas  implements java.io.Serializable {


     private String cuenta;
     private String correo;
     private String password;
     private String usuario;

    public Cuentas() {
    }

	
    public Cuentas(String cuenta, String correo) {
        this.cuenta = cuenta;
        this.correo = correo;
    }
    public Cuentas(String cuenta, String correo, String password, String usuario) {
       this.cuenta = cuenta;
       this.correo = correo;
       this.password = password;
       this.usuario = usuario;
    }
   
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }




}


